# Site settings
title: Alejandro Pena Lorenzo
description: Personal portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alejandro Pena
user_title: Software Engineer
email: info@alejandropena.dev
twitter_username: apenlor
github_username:  gbtec-ext-alejandropenaalopezsanchez

# Google-analytics
google_analytics: true
google_analytics_id: UA-135913298-1

exclude: ['package.json', 'src' , 'node_modules']
